### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [TathanDev/StarWarsPlanets#1]
My game crash at startup when i use this mod. I dont know why. :(
Can you help me?
[crash-2022-05-20_10.56.28-client.txt](https://github.com/TathanDev/StarWarsPlanets/files/8738036/crash-2022-05-20_10.56.28-client.txt)

**Comment by agentwolf88** [comment]
One more crashlog
[crash-2022-05-20_11.50.37-fml.txt](https://github.com/TathanDev/StarWarsPlanets/files/8738408/crash-2022-05-20_11.50.37-fml.txt)

**Comment by remplerus** [comment]
i get that second one too. but the first one might be another mod not registering their things in right spot, as that mod is refreezing. so just check mods (especially the mods adding custom recipes)

**Comment by TathanDev** [comment]
Ok i know the problem. 
For the moment, i use Beyond Earth 6.2-DEV but you use 6.1.
You need to use this version (Don't look the name, it is the the dev version) https://github.com/TathanDev/StarWarsPlanets/blob/main/libs/net/mrscauthd/beyond_earth/1.18.2-6.0/beyond_earth-1.18.2-6.0.jar

Thanks to report this issues^^

**Comment by agentwolf88** [comment]
Does not  work :(
[crash-2022-05-25_11.55.07-fml.txt](https://github.com/TathanDev/StarWarsPlanets/files/8769961/crash-2022-05-25_11.55.07-fml.txt)

**Comment by TathanDev** [comment]
Ok try this https://cdn.discordapp.com/attachments/972784330713759764/972911172863025232/beyond_earth-1.18.2-6.0.jar

**Comment by TathanDev** [comment]
Or try without Beyond dimensions for test

**Comment by agentwolf88** [comment]
With the new version of beyond earth and without beyond dimensions the game crashs without crashlog.
[latest.log](https://github.com/TathanDev/StarWarsPlanets/files/8773420/latest.log)
[debug.log](https://github.com/TathanDev/StarWarsPlanets/files/8773421/debug.log)

**Comment by agentwolf88** [comment]
With the "old" version and without beyond dimensions the game crashs with crashlog.
[crash-2022-05-25_19.49.43-fml.txt](https://github.com/TathanDev/StarWarsPlanets/files/8773453/crash-2022-05-25_19.49.43-fml.txt)

**Comment by TathanDev** [comment]
Ok i check this

**Comment by TathanDev** [comment]
@agentwolf88 in fue days, the final version of Beyond Earth 6.2 will be release. After this, i will do some test with other mod to fix things.

**Comment by TathanDev** [comment]
This issue should be fixed with the New version.
Be sure to use the latest version of Beyond Earth

**Comment by agentwolf88** [comment]
Still crashs. :)

[crash-2022-06-01_11.53.06-fml.txt](https://github.com/TathanDev/StarWarsPlanets/files/8813073/crash-2022-06-01_11.53.06-fml.txt)

**Comment by TathanDev** [comment]
Ok now the problem should be solved with the latest version.
MrScautHd gave me the 6.2 Dev build but not the 6.2 release.
This is the link for the file : https://www.curseforge.com/minecraft/mc-mods/star-wars-planets/files/3813664

**Comment by TathanDev** [comment]
The problem is fix ?

**Comment by TathanDev** [comment]
I close this issues because i don't have news so....
